Theme: Waste Manageement

Title: RecyleLens

Description: RecycleLens merupakan aplikasi pengklasifikasian sampah berbasis AI dengan memanfaatkan image processing. Pengguna hanya perlu memindai sampah yang hendak dibuang, lalu aplikasi kami akan memberikan hasil klasifikasi sampah dari pemindaian sampah pengguna. Tak hanya itu, aplikasi kami juga menyediakan fitur-fitur lainnya seperti peta lokasi,panduan klasifikasi, dan artikel. Pengembangan fitur ini bertujuan untuk memberikan pengalaman pengguna yang lebih baik.


